import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { Loader2, ShieldCheck } from "lucide-react";

/**
 * A5 — TOTP enrollment page. Shown to admin/CEO without an active factor.
 * Uses Supabase Auth native MFA (no recovery codes — admins reset via DB).
 */
export default function MfaEnroll() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const next = params.get("next") || "/dashboard";
  const { isAdmin, isCeo, isLoading: authLoading } = useAuth();

  const [loading, setLoading] = useState(true);
  const [factorId, setFactorId] = useState<string | null>(null);
  const [qrSvg, setQrSvg] = useState<string | null>(null);
  const [secret, setSecret] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [verifying, setVerifying] = useState(false);

  useEffect(() => {
    if (authLoading) return;
    if (!isAdmin && !isCeo) {
      navigate(next, { replace: true });
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        // If a verified factor already exists, skip enrollment
        const { data: list } = await supabase.auth.mfa.listFactors();
        const existing = (list?.totp ?? []).find((f) => f.status === "verified");
        if (existing) {
          navigate(next, { replace: true });
          return;
        }
        // Drop any pending unverified factor before enrolling a new one
        const pending = (list?.totp ?? []).filter((f) => f.status !== "verified");
        for (const p of pending) {
          await supabase.auth.mfa.unenroll({ factorId: p.id });
        }
        const { data, error } = await supabase.auth.mfa.enroll({
          factorType: "totp",
          friendlyName: `CRM ${new Date().toISOString().slice(0, 10)}`,
        });
        if (cancelled) return;
        if (error || !data) {
          toast.error(error?.message || "Errore avvio enrollment MFA");
          return;
        }
        setFactorId(data.id);
        setQrSvg(data.totp.qr_code);
        setSecret(data.totp.secret);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [authLoading, isAdmin, isCeo, navigate, next]);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!factorId || code.length !== 6) return;
    setVerifying(true);
    try {
      const { data: ch, error: chErr } = await supabase.auth.mfa.challenge({ factorId });
      if (chErr || !ch) {
        toast.error(chErr?.message || "Errore challenge");
        return;
      }
      const { error: vErr } = await supabase.auth.mfa.verify({
        factorId,
        challengeId: ch.id,
        code,
      });
      if (vErr) {
        toast.error(vErr.message || "Codice non valido");
        return;
      }
      // A6: audit MFA enrollment
      void import("@/lib/session-audit").then(({ logSessionEvent }) =>
        logSessionEvent("mfa_enroll"),
      );
      toast.success("MFA attivato. La sessione è ora protetta.");
      navigate(next, { replace: true });
    } finally {
      setVerifying(false);
    }
  };

  if (authLoading || loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-background via-background to-muted p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center space-y-1">
          <ShieldCheck className="mx-auto h-10 w-10 text-primary mb-2" />
          <CardTitle className="text-2xl font-bold">Attiva MFA</CardTitle>
          <CardDescription>
            Il tuo ruolo richiede un secondo fattore (TOTP). Inquadra il QR con
            Google Authenticator, 1Password, Authy o simili.
          </CardDescription>
        </CardHeader>
        <form onSubmit={handleVerify}>
          <CardContent className="space-y-4">
            {qrSvg && (
              <div
                className="flex items-center justify-center rounded-lg border bg-white p-4"
                // SVG generated by Supabase, safe — but we still scope styling
                dangerouslySetInnerHTML={{ __html: qrSvg }}
                aria-label="QR code TOTP"
              />
            )}
            {secret && (
              <div className="text-xs text-muted-foreground text-center break-all">
                Codice manuale:&nbsp;
                <span className="font-mono">{secret}</span>
              </div>
            )}
            <div className="space-y-2">
              <Label htmlFor="otp">Codice a 6 cifre</Label>
              <Input
                id="otp"
                inputMode="numeric"
                pattern="\d{6}"
                maxLength={6}
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                autoComplete="one-time-code"
                required
                disabled={verifying}
              />
            </div>
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full" disabled={verifying || code.length !== 6}>
              {verifying ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Verifica…
                </>
              ) : (
                "Attiva e prosegui"
              )}
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}
