/**
 * useCreateSalesOrderFromAppointment — creates a standalone sales order
 * linked to a contact (and optionally a deal) starting from an appointment.
 * order_number is auto-generated by DB trigger.
 */
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { useWriteBrandId } from "@/hooks/useWriteBrandId";
import { untypedClient } from "@/integrations/supabase/untypedClient";

export interface CreateOrderFromAppointmentInput {
  appointmentId: string;
  contactId: string;
  dealId?: string | null;
}

export function useCreateSalesOrderFromAppointment() {
  const qc = useQueryClient();
  const { user } = useAuth();
  const { getWriteBrandId } = useWriteBrandId();

  return useMutation({
    mutationFn: async (input: CreateOrderFromAppointmentInput): Promise<string> => {
      const brandId = getWriteBrandId();
      const { data, error } = await untypedClient
        .from("sales_orders")
        .insert({
          brand_id: brandId,
          contact_id: input.contactId,
          deal_id: input.dealId || null,
          assigned_user_id: user?.id ?? null,
          status: "confirmed",
          confirmed_at: new Date().toISOString(),
          subtotal: 0,
          tax_amount: 0,
          total_amount: 0,
          paid_amount: 0,
          discount_amount: 0,
          notes: `Vendita da appuntamento ${input.appointmentId}`,
        })
        .select("id")
        .single();

      if (error) throw error;
      return (data as { id: string }).id;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["sales-orders"] });
    },
    onError: () => {
      toast.error("Errore nella creazione della vendita");
    },
  });
}
